# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacherSolution.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeacherSolution(object):
    def setupUi(self, TeacherSolution):
        TeacherSolution.setObjectName("TeacherSolution")
        TeacherSolution.resize(664, 314)
        self.centralwidget = QtWidgets.QWidget(TeacherSolution)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 18))
        self.label.setObjectName("label")
        self.selected_groups = QtWidgets.QTableWidget(self.centralwidget)
        self.selected_groups.setGeometry(QtCore.QRect(10, 30, 291, 41))
        self.selected_groups.setObjectName("selected_groups")
        self.selected_groups.setColumnCount(0)
        self.selected_groups.setRowCount(0)
        TeacherSolution.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TeacherSolution)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 30))
        self.menubar.setObjectName("menubar")
        TeacherSolution.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TeacherSolution)
        self.statusbar.setObjectName("statusbar")
        TeacherSolution.setStatusBar(self.statusbar)

        self.retranslateUi(TeacherSolution)
        QtCore.QMetaObject.connectSlotsByName(TeacherSolution)

    def retranslateUi(self, TeacherSolution):
        _translate = QtCore.QCoreApplication.translate
        TeacherSolution.setWindowTitle(
            _translate(
                "TeacherSolution",
                "Teacher Solution"))
        self.label.setText(_translate("TeacherSolution", "Selected Groups"))
