# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacherSolution.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeacherSolution(object):
    def setupUi(self, TeacherSolution):
        TeacherSolution.setObjectName("TeacherSolution")
        TeacherSolution.resize(377, 208)
        self.centralwidget = QtWidgets.QWidget(TeacherSolution)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.selected_groups = QtWidgets.QTableWidget(self.centralwidget)
        self.selected_groups.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.selected_groups.setObjectName("selected_groups")
        self.selected_groups.setColumnCount(0)
        self.selected_groups.setRowCount(0)
        self.verticalLayout.addWidget(self.selected_groups)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        TeacherSolution.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TeacherSolution)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 377, 30))
        self.menubar.setObjectName("menubar")
        TeacherSolution.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TeacherSolution)
        self.statusbar.setObjectName("statusbar")
        TeacherSolution.setStatusBar(self.statusbar)

        self.retranslateUi(TeacherSolution)
        QtCore.QMetaObject.connectSlotsByName(TeacherSolution)

    def retranslateUi(self, TeacherSolution):
        _translate = QtCore.QCoreApplication.translate
        TeacherSolution.setWindowTitle(
            _translate(
                "TeacherSolution",
                "Teacher Solution"))
        self.label.setText(_translate("TeacherSolution", "Selected Groups"))
