name: PyInstallerLinux

on:
  push:
    branches:
      - master


jobs:
  buildLin:
    needs: autopep8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Install pyinstaller
      run: pip install pyinstaller

    - name: Pyinstaller
      run: python -m PyInstaller ./main.spec

    - uses: actions/upload-artifact@v2
      with:
        name: linux_build
        path: dist
