name: PyInstallerLinux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip wheel;
        pip install -r requirements/install.txt;
        pip install -r requirements/dev.txt;
        pip install --no-deps .
    - name: PyInstaller
      run: |
        python -m PyInstaller -y\
          --add-binary\
          "/home/wd/.conda/envs/pySprida/lib/python3.8/site-packages/mip/libraries/win64/*:mip/libraries/win64"\
          --add-binary\
          "/home/wd/.conda/envs/pySprida/lib/python3.8/site-packages/mip/libraries/lin64/*:mip/libraries/lin64/"\
          --add-binary\
          "/home/wd/.conda/envs/pySprida/lib/python3.8/site-packages/mip/libraries/cbc-c-darwin-x86-64.dylib:mip/libraries"\
          ./scripts/main.py\
