name: PyInstallerWindows

on: [push]

jobs:
  buildWin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: main.spec

    - uses: actions/upload-artifact@v2
      with:
        name: windows_build
        path: dist/windows
