name: PyInstallerLinux

on: [push]

jobs:
  buildLin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .
        spec: main.spec

    - uses: actions/upload-artifact@v2
      with:
        name: linux_build
        path: dist/linux
